### ISSUE TITLE
Placeholder grid-1-column contains unknown component ContentBlock. Ensure that a React component exists for it, and that it is registered in your componentFactory.js.

### ISSUE THREAD

**Issue by bartohos** [anastasiya29/sitecore-jss-grid-components#1]
Hello, When running the sandBox application that refers to this repo. I have this error `Placeholder grid-1-column contains unknown component ContentBlock. Ensure that a React component exists for it and that it is registered in your componentFactory.js.` 
![image](https://user-images.githubusercontent.com/43158305/65963844-979dbd00-e429-11e9-9e03-51e5b5188c81.png)
but the `ContentBlock` component is added to my component factory and when replacing the en.yml file of the sandbox with this 
```
id: home-page
fields:
  pageTitle: Welcome to Sitecore JSS
placeholders:
  jss-main:
  - componentName: ContentBlock
    fields:
      heading: Welcome to Sitecore JSS
      content: JSS Sandbox
```
it's able to show the ContentBlock component.
Could you help me with that, please? Thank you
